1. What exactly is []?

2. In a list of values stored in a variable called spam, how would you assign the value 'hello' as the third value? (Assume [2, 4, 6, 8, 10] are in spam.)

In [7]:
spam = [2,4,6,8,10]

In [8]:
spam.insert(2,'hello')

In [9]:
spam

[2, 4, 'hello', 6, 8, 10]

Let's pretend the spam includes the list ['a', 'b', 'c', 'd'] for the next three queries.

3. What is the value of spam[int(int('3' * 2) / 11)]?

In [10]:
spam = ['a', 'b', 'c', 'd']

In [11]:
spam[int(int('3' * 2) / 11)]

'd'

4. What is the value of spam[-1]?

In [15]:
spam[-1]

'd'

5. What is the value of spam[:2]?

In [17]:
spam[:2]

['a', 'b']

Let's pretend bacon has the list [3.14, 'cat,' 11, 'cat,' True] for the next three questions.

6. What is the value of bacon.index('cat')?

In [19]:
bacon = [3.14, 'cat', 11, 'cat', True]

In [20]:
bacon.index('cat')

1

7. How does bacon.append(99) change the look of the list value in bacon?

In [21]:
bacon.append(99)

In [23]:
# It appends the value 99 at the end of the list
bacon

[3.14, 'cat', 11, 'cat', True, 99]

8. How does bacon.remove('cat') change the look of the list in bacon?

In [24]:
bacon.remove('cat')

In [25]:
#It removes the first occurence of 'cat' from the list
bacon

[3.14, 11, 'cat', True, 99]

9. What are the list concatenation and list replication operators?

10. What is difference between the list methods append() and insert()?

In [45]:
# Eg:-
a = [1,2,3,4,5]
print("Original List: " ,a)
a.append(10)
print("Output after append method: " ,a)
a.insert(2,20)
print("Output after insert method: " ,a)

Original List:  [1, 2, 3, 4, 5]
Output after append method:  [1, 2, 3, 4, 5, 10]
Output after insert method:  [1, 2, 20, 3, 4, 5, 10]


11. What are the two methods for removing items from a list?

In [46]:
# Eg:-
print("Original List: " ,a)
a.pop(3)
print("Output after pop method: " , a)
a.remove(10)
print("Output after remove method: " ,a)

Original List:  [1, 2, 20, 3, 4, 5, 10]
Output after pop method:  [1, 2, 20, 4, 5, 10]
Output after remove method:  [1, 2, 20, 4, 5]


12. Describe how list values and string values are identical.

13. What's the difference between tuples and lists?

In [54]:
# Eg:-

l = [1,2,3,4,5]
print("Original List: ", l)
l[2] = 13
print("Updated List: ", l)

t = (1,2,3,4,5)
print("Orininal Tuple: ",t)
t[3] = 13
print("Updated Tuple: ",t)            #--------- Error Because tuples are immutable, item assignment will not happen----- #

Original List:  [1, 2, 3, 4, 5]
Updated List:  [1, 2, 13, 4, 5]
Orininal Tuple:  (1, 2, 3, 4, 5)


TypeError: 'tuple' object does not support item assignment

14. How do you type a tuple value that only contains the integer 42?

In [52]:
tuple((23,))

(23,)

15. How do you get a list value's tuple form? How do you get a tuple value's list form?

In [68]:
t = (1,2,3,4,5)
print("Original Tuple: ",t)
print("Tuple Modified in the form of list: ",list(t))

print("------------------------------------")

l = [6,7,8,9,10]
print("Original List: ", l)
print("List Modified in the form of Tuple: ",tuple(l))

Original Tuple:  (1, 2, 3, 4, 5)
Tuple Modified in the form of list:  [1, 2, 3, 4, 5]
------------------------------------
Original List:  [6, 7, 8, 9, 10]
List Modified in the form of Tuple:  (6, 7, 8, 9, 10)


16. Variables that "contain" list values are not necessarily lists themselves. Instead, what do they contain?

17. How do you distinguish between copy.copy() and copy.deepcopy()?

In [109]:
import copy
import numpy as np

In [116]:
#Eg:-
    
arr = np.array([[1,4],[3,4]])

In [117]:
# Shallow Copy
a = arr                      # -------------- It will get created at the same place where arr is ---------- #

In [118]:
# Deep Copy 
b = np.copy(arr)             # --------------- It will create a new place in memory ---------------- #

In [119]:
arr[0][0] = 67

In [120]:
arr

array([[67,  4],
       [ 3,  4]])

In [121]:
a

array([[67,  4],
       [ 3,  4]])

In [122]:
b

array([[1, 4],
       [3, 4]])